export {default as Login} from './auth/login'
export {default as Register} from './auth/register'
export {default as HomeLayout} from './homeLayout'
export {default as DashboardLayout} from './dashboardLayout'
export {default as Error} from './error'
export {default as LandingLayout} from './landingLayout'
export {default as Activation} from './auth/activation'