export {default as Login} from './auth/login'
export {default as Register} from './auth/register'
export {default as Error} from './error'
export {default as Activation} from './auth/activation'
export {default as HomePage} from './homePage'
export {default as AppContainer} from './appContainer'